#!/usr/bin/env python

import h5py as h5
from sys import argv
from glob import glob


for g in argv[1:]:
    for inFN in glob(g):
        f = h5.File(inFN)
        try:
            framecount = f['rayonix'].shape[0]
        except:
            framecount = None
        print("{}\t{}".format(inFN, framecount))

